# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5e6912d50cf22895e3c87e9f5754a4bf8af54ff70c77cd07b2b60eb1ff2b69ea232cba683591c3e3758606c30a40a6c20763ad8a285ea8ae4194913b7380dd6e

test:
  secret_key_base: d6be39a25b99657ee78f9f54f200b1fc9b0f891f8ef3304b4af766b25308d4194517ec5fe9ad2c9e75d2a6e7417570cb7c5444203fc948bb3a22447a106a0017

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
